[build]
  publish = "public"

# Backend proxy to Render
[[redirects]]
  from = "/api/*"
  to = "https://incident-reporter-1.onrender.com/api/:splat"
  status = 200
  force = true

# Proxy Socket.IO (WebSocket) endpoints to the backend
[[redirects]]
  from = "/socket.io/*"
  to = "https://incident-reporter-1.onrender.com/socket.io/:splat"
  status = 200
  force = true
