services:
  - type: web
    name: incident-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: GEOAPIFY_API_KEY
        sync: false
